# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OpenMovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.9.1'
  pod 'Kingfisher', '~> 5.0'
  
  # Pods for OpenMovieDB

  target 'OpenMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenMovieDBUITests' do
    # Pods for testing
  end

end
